name: Transform lab config

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Generate README
        uses: wix-academy/github-lab-config-to-github-skills-readme-action@v4.2
        with:
          config-file: 'config.yml'
          course-details-file: 'course-details.md'
          readme-file: 'README.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_READ_ACCESS_TOKEN }}
          
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "generate README.md from config.yml + course-details.md"
